name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Create tag
        id: create_tag
        run: |
          VERSION=$(./build_version.sh)
          echo "Generated version number: ${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV  # Store VERSION in environment
          git tag v${VERSION}
          git push origin v${VERSION}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Start the Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload: |
            {
              "text": "New version v${{ env.VERSION }} has been deployed! 🚀",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*New Release Deployed! 🎉*\nVersion: v${{ env.VERSION }}\nRepository: ${{ github.repository }}"
                  }
                }
              ]
            }
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
